# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155ZJ7ctA9GXD5_bR7TPvWLXAKDMBWtlr
"""

!pip install nltk streamlit

import string
import nltk
from nltk.tokenize import word_tokenize

# Ensure necessary NLTK data is downloaded
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords

def preprocess(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Tokenize the text
    words = word_tokenize(text)

    # Remove stop words
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    return ' '.join(words)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def get_most_relevant_sentence(query, text):
    # Preprocess the text and query
    sentences = text.split('.')
    sentences = [preprocess(sentence) for sentence in sentences]

    # Add the user's query to the list of sentences
    sentences.append(preprocess(query))

    # Vectorize the sentences and the query
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(sentences)

    # Compute cosine similarity between the query and each sentence
    cosine_similarities = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1])

    # Get the index of the most relevant sentence
    most_relevant_idx = cosine_similarities.argmax()

    return sentences[most_relevant_idx]

def chatbot(query, text):
    return get_most_relevant_sentence(query, text)

import streamlit as st

def main():
    # The text for the chatbot (you could also load this from a text file)
    text = """
    Data science is an interdisciplinary field that uses scientific methods, algorithms, and systems to extract knowledge and insights from structured and unstructured data. It is a rapidly growing field that has applications in industries ranging from healthcare to finance, marketing, and more.

    Key Concepts in Data Science
    1. Data Collection: The process of gathering data from various sources such as surveys, sensors, and web scraping.
    2. Data Cleaning: Ensuring data quality by handling missing values, removing duplicates, and standardizing formats.
    3. Data Analysis: Applying statistical techniques to summarize and interpret data.
    4. Machine Learning: Using algorithms to identify patterns and make predictions or decisions based on data.
    5. Data Visualization: Representing data graphically using tools like Matplotlib, Tableau, or Power BI.

    Applications of Data Science
    - Healthcare: Predicting disease outbreaks, optimizing patient care, and personalizing treatments.
    - Finance: Detecting fraud, managing risk, and improving customer segmentation.
    - Retail: Recommending products and optimizing inventory.
    - Transportation: Improving route planning and predictive maintenance.

    Skills Required for Data Scientists
    Data scientists need expertise in programming languages like Python and R, knowledge of machine learning algorithms, and familiarity with data visualization tools. Strong communication skills are also essential for explaining technical insights to non-technical stakeholders.

    Challenges in Data Science
    1. Data Privacy: Ensuring compliance with regulations like GDPR.
    2. Bias in Data: Avoiding biased models caused by unrepresentative data.
    3. Scalability: Managing large datasets efficiently.

    Data science continues to evolve, driving innovation across multiple sectors and transforming how decisions are made.
    """

    # Chatbot introduction
    st.title("Data Science Chatbot")
    st.write("Ask me anything about Data Science!")

    # User input
    query = st.text_input("Your question:")

    if query:
        # Get the chatbot response
        response = chatbot(query, text)
        st.write(f"Response: {response}")

if __name__ == "__main__":
    main()

pip install nltk scikit-learn streamlit

!pip install streamlit
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# 
# 
# 
# 
# 
# 
# %%writefile data_science_chatbot.py
# 
# import string
# import nltk
# from nltk.tokenize import word_tokenize
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# import streamlit as st
# 
# nltk.download('punkt')
# nltk.download('stopwords')
# from nltk.corpus import stopwords
# 
# # Preprocess function
# def preprocess(text):
#     text = text.lower()
#     text = text.translate(str.maketrans('', '', string.punctuation))
#     words = word_tokenize(text)
#     stop_words = set(stopwords.words('english'))
#     words = [word for word in words if word not in stop_words]
#     return ' '.join(words)
# 
# # Similarity function
# def get_most_relevant_sentence(query, text):
#     sentences = text.split('.')
#     sentences = [preprocess(sentence) for sentence in sentences]
#     sentences.append(preprocess(query))
#     vectorizer = TfidfVectorizer()
#     tfidf_matrix = vectorizer.fit_transform(sentences)
#     cosine_similarities = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1])
#     most_relevant_idx = cosine_similarities.argmax()
#     return sentences[most_relevant_idx]
# 
# # Chatbot function
# def chatbot(query, text):
#     return get_most_relevant_sentence(query, text)
# 
# # Streamlit app
# def main():
#     text = """
#     Data science is an interdisciplinary field that uses scientific methods, algorithms, and systems to extract knowledge and insights from structured and unstructured data. It is a rapidly growing field that has applications in industries ranging from healthcare to finance, marketing, and more.
# 
#     Key Concepts in Data Science
#     1. Data Collection: The process of gathering data from various sources such as surveys, sensors, and web scraping.
#     2. Data Cleaning: Ensuring data quality by handling missing values, removing duplicates, and standardizing formats.
#     3. Data Analysis: Applying statistical techniques to summarize and interpret data.
#     4. Machine Learning: Using algorithms to identify patterns and make predictions or decisions based on data.
#     5. Data Visualization: Representing data graphically using tools like Matplotlib, Tableau, or Power BI.
#     """
# 
#     st.title("Data Science Chatbot")
#     st.write("Ask me anything about Data Science!")
# 
#     query = st.text_input("Your question:")
# 
#     if query:
#         response = chatbot(query, text)
#         st.write(f"Response: {response}")
# 
# if __name__ == "__main__":
#     main()
#

import streamlit as st

def main():
    # The text for the chatbot (you could also load this from a text file)
    text = """
    Data science is an interdisciplinary field that uses scientific methods, algorithms, and systems to extract knowledge and insights from structured and unstructured data. It is a rapidly growing field that has applications in industries ranging from healthcare to finance, marketing, and more.

    Key Concepts in Data Science
    1. Data Collection: The process of gathering data from various sources such as surveys, sensors, and web scraping.
    2. Data Cleaning: Ensuring data quality by handling missing values, removing duplicates, and standardizing formats.
    3. Data Analysis: Applying statistical techniques to summarize and interpret data.
    4. Machine Learning: Using algorithms to identify patterns and make predictions or decisions based on data.
    5. Data Visualization: Representing data graphically using tools like Matplotlib, Tableau, or Power BI.

    Applications of Data Science
    - Healthcare: Predicting disease outbreaks, optimizing patient care, and personalizing treatments.
    - Finance: Detecting fraud, managing risk, and improving customer segmentation.
    - Retail: Recommending products and optimizing inventory.
    - Transportation: Improving route planning and predictive maintenance.

    Skills Required for Data Scientists
    Data scientists need expertise in programming languages like Python and R, knowledge of machine learning algorithms, and familiarity with data visualization tools. Strong communication skills are also essential for explaining technical insights to non-technical stakeholders.

    Challenges in Data Science
    1. Data Privacy: Ensuring compliance with regulations like GDPR.
    2. Bias in Data: Avoiding biased models caused by unrepresentative data.
    3. Scalability: Managing large datasets efficiently.

    Data science continues to evolve, driving innovation across multiple sectors and transforming how decisions are made.
    """

    # Chatbot introduction
    st.title("Data Science Chatbot")
    st.write("Ask me anything about Data Science!")

    # User input
    query = st.text_input("Your question:")

    if query:
        # Get the chatbot response
        response = chatbot(query, text)
        st.write(f"Response: {response}")

if __name__ == "__main__":
    main()

from pyngrok import ngrok

# Ouvrir un tunnel sur le port 8501 pour Streamlit
public_url = ngrok.connect(8501)
print(f"Streamlit app accessible at: {public_url}")

from pyngrok import ngrok

# Ajoutez votre authtoken ici
ngrok.set_auth_token("2q4KByztntzAOx7hdjkSEAZ455s_31sy5bfngpwHkM7bNX9uS")

# Ouvrir un tunnel sur le port 8501 pour Streamlit
public_url = ngrok.connect(8501)
print(f"Streamlit app accessible at: {public_url}")

!streamlit run data_science_chatbot.py &